# ===================================
#  Form Behavior Config
# ===================================

name: indikator.marketing::lang.title.projects
form: ~/plugins/indikator/marketing/models/projects/fields.yaml

modelClass: Indikator\Marketing\Models\Projects
defaultRedirect: indikator/marketing/projects

create:
    redirect: indikator/marketing/projects/update/:id
    redirectClose: indikator/marketing/projects

update:
    redirect: indikator/marketing/projects/update/:id
    redirectClose: indikator/marketing/projects
